### ISSUE TITLE
Runtime error on real generated page script: 'getElementById'/'querySelector' is not a function

### ISSUE THREAD

**Issue by tkfinitefield** [finitefield-org/browser-tester#26]
## Summary
`browser_tester` runtime fails on a generated real-world page script with:

- `ScriptRuntime("'getElementById' is not a function")`
- `ScriptRuntime("'querySelector' is not a function")`

This happens during `Harness::from_html(...)` for `/tools/wholesale/bundle-cost-margin/` tests in `ff-cli`.

## Environment
- browser_tester: local path dependency at commit `d4fc9b8`
- rustc: `1.92.0 (ded5c06cf 2025-12-08)`
- OS: `Darwin 25.2.0 arm64`

## Reproduction
From `finitefield-site/web-rust`:

```bash
cargo test -p ff-cli --test wholesale_bundle_cost_margin_browser_test -- --nocapture --test-threads=1
```

## Actual result
All 10 tests fail with runtime errors. Typical output:

```text
test brt_001_open_button_shows_fullscreen_dialog ... Error: ScriptRuntime("'getElementById' is not a function")
test brt_003_calculates_set_cost_and_min_price_for_basic_case ... Error: ScriptRuntime("'querySelector' is not a function")
```

## Expected result
The page script should execute in browser_tester runtime (or return a precise unsupported-feature error), and standard DOM APIs should remain callable.

## Notes
- Basic minimal probes for `document.getElementById(...)` pass in isolation.
- The failure appears only when running this generated page script (larger realistic script).
- `#[ignore]` is not used for these tests.

**Comment by tkfinitefield** [comment]
Follow-up (clean summary):

Fixed in runtime dispatch for document member calls.

- Added document-object member call routing for dynamic arguments: getElementById, querySelector, querySelectorAll, addEventListener, removeEventListener.
- Added regression coverage in tests/regression_real_world_html.rs (document_member_calls_with_dynamic_arguments_are_supported).

Validation:
- cargo test -q -p ff-cli --test wholesale_bundle_cost_margin_browser_test -- --test-threads=1 --nocapture
- The original common errors ('getElementById' is not a function, 'querySelector' is not a function) no longer appear.
